version: "3.7"

services:
  cells:
    image: pydio/cells:latest
    restart: always
    ports:
      - "172.17.0.1:8564:80"
    environment:
      - CELLS_BIND=${PUBLIC_FQDN}:443
      - CELLS_EXTERNAL=https://${PUBLIC_FQDN}
      - CELLS_LE_AGREE=1
      - CELLS_LE_EMAIL=${ADMIN_EMAIL}
      - CELLS_INSTALL_YAML=/pydio/config/install.yml
      - CELLS_ADMIN_PWD=${CELLS_ADMIN_PWD}
      - MYSQL_PYDIO_PWD=${MYSQL_PYDIO_PWD}
    volumes:
      - ./cellsdir:/var/cells
      - ./install-conf.yml:/pydio/config/install.yml:ro

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: cells
      MYSQL_USER: pydio
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./mysqldir:/var/lib/mysql
    command:
      [
        mysqld,
        --character-set-server=utf8mb4,
        --collation-server=utf8mb4_unicode_ci,
      ]
